In [1]:
pip install opencv-python

Note: you may need to restart the kernel to use updated packages.


In [17]:
import cv2
import numpy as np
from matplotlib import pyplot as plt
import math
import pandas as pd
%matplotlib inline

from sklearn.neighbors import KNeighborsClassifier


In [11]:
img = cv2.imread("res.jpg")
print(type(img))

lab = cv2.cvtColor(img, cv2.COLOR_RGB2LAB)
print(lab[150][500:520])

<class 'numpy.ndarray'>
[[188 119 102]
 [188 120 102]
 [188 121 102]
 [188 121 102]
 [189 119 103]
 [189 119 103]
 [188 119 103]
 [188 119 103]
 [189 119 103]
 [189 119 103]
 [190 119 103]
 [190 119 103]
 [192 119 103]
 [191 119 103]
 [190 119 103]
 [189 119 103]
 [189 119 103]
 [189 119 103]
 [189 119 103]
 [189 119 103]]


In [15]:
df = pd.read_excel('Color RGB List.xlsx')
X = df.drop(['Color'], axis=1)
Y = df['Color']
print(dataset)

      r    g    b   Color
0   217  160   91    gold
1   170  106   53    gold
2   189  125   62    gold
3   198  138   78    gold
4   205  138   66    gold
5   225  198  153   beige
6   237  198  147   beige
7   216  174  118   beige
8   214  168  115   beige
9   233  196  141   beige
10   90  183   39   green
11   72  177   30   green
12   76  135   39   green
13  153  205  103   green
14   87  184   33   green
15   33  121  171    blue
16   31  123  176    blue
17   17  103  170    blue
18   48   84  118    blue
19    2   94  149    blue
20  254  134   29  orange
21  233   99   20  orange
22  236  108   23  orange
23  251  144   54  orange
24  219   89   18  orange


In [22]:
clf = KNeighborsClassifier()
clf.fit(X,Y)
y_pred = clf.predict([[93,166,38]])
print(y_pred)

['green']
